routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Route::get('/', 'MapController@index');

//Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::resource('gates', 'ListsController');

Route::resource('branches', 'BranchController');

Route::resource('roads', 'RoadsController');

Route::resource('virtuals', 'VirtualController');

Route::resource('details', 'DetailController');


Route::get('/map', 'MapController@index');

Route::get('gates/branch_detail/{id}', 'ListsController@branch_detail')->name('branch_detail');
Route::get('details/gate_info/{id}', 'DetailController@gate_info')->name('gate_info');
Route::get('details/virtual/{id}', 'DetailController@virtual')->name('gate_code');
Route::get('details/gate_maps/{id}', 'DetailController@gate_maps')->name('gate_maps');

app/gate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class gate extends Model
{
    protected $fillable = ['branch_info','gate_name','gate_code','list_adress','langitude','longitude','radius'];
}

resources/views/gates/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create Gate</div>
                    <div class="card-body">
                        @include('validate')
                        {!! Form::open(['route'=>'gates.store','method'=>'post']) !!}

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Gate Name</label>
                            <div class="col-md-4">
                                {!! Form::text('list_name', null, ['class'=>'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Gate Address</label>
                            <div class="col-md-4">
                                {!! Form::text('list_adress', null, ['class'=>'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Lang</label>
                            <div class="col-md-4">
                                {!! Form::text('langitude', null, ['class'=>'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Long</label>
                            <div class="col-md-4">
                                {!! Form::text('longitude', null, ['class'=>'form-control']) !!}
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-2">
                                <button type="submit" class="btn btn-secondary btn-sm">add</button>
                                <a href=" {{ route('gates.index') }}" class="btn btn-secondary btn-sm">back</a>
                            </div>
                        </div>
                                <div class="card-header">Our Location</div>
                                <div id="map"></div>
                                <div class="content"></div>
                                <div style="width: 1000px; height: 500px;">
                                    {!! Mapper::render() !!}
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    {{-- <script>
        // Initialize and add the map
        function initMap()
        {
          // The location of Indonesia
          var Indonesia = {lat: -6.200000	,  lng: 106.816666};
          // The map, centered at Indonesia
          var map = new google.maps.Map(
              document.getElementById('map'), {zoom: 8, center: indonesia});
          // The marker, positioned at Indonesia
          var marker = new google.maps.Marker ({position: indonesia, map: map});
        }
            </script>
            <!--Load the API from the specified URL
            * The async attribute allows the browser to render the page while the API loads
            * The key parameter will contain your own API key (which is not needed for this tutorial)
            * The callback parameter executes the initMap() function
            -->
            <script
            {{-- async defer --}}
            {{-- <div class="content">
                <div style="width: 1000px; height: 500px;">
                    {!! Mapper::render() !!}
                </div>
            </div> --}}
            {{-- src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMyjXZUcSAiFz2j_qf7K1HLof1tgl_RsU&libraries=places&language=id">
           src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMyjXZUcSAiFz2j_qf7K1HLof1tgl_RsU&callback=initMap">
    </script> --}} 

@endsection

resources/views/gates/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">List Gates</div>
                    @include('notif')
                    <div class ="card-body">
                        <th><a href=" {{ route('gates.create') }}" class="btn btn-primary btn-sm" ><i class="fas fa-plus-circle"></i> Create New Gates</a></th>
                    </div>
                        <table class="table table-bordered" id="users-table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Branch Code</th>
                                    <th>Gate Name</th>
                                    <th>Gate Code</th>
                                    <th>Gate Adress</th>
                                    <th>Lat</th>
                                    <th>Long</th>
                                    <th>Radius</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ( $gates as $gate )
                                <tr>
                                    <th>{{ $loop->iteration }}</th>
                                    <th>{{ $gate->branch_info }}</th>
                                    <th>{{ $gate->gate_name }}</th>
                                    <th>{{ $gate->gate_code }}</th>
                                    <th>{{ $gate->list_adress }}</th>
                                    <th>{{ $gate->langitude }}</th>
                                    <th>{{ $gate->longitude }}</th>
                                    <th>{{ $gate->radius }}</th>
                                    <td>
                                        {!! Form::open(['route'=>['gates.destroy',$gate->id],'method'=>'DELETE']) !!}
                                        <a href="{{ route('gates.show',$gate->id) }}" class="btn"><i class="fas fa-info-circle"></i></a>
                                        <a href=" {{ route('gates.edit',$gate->id) }}" class="btn"><i class="fas fa-edit"></i></a>
                                        <button class="btn" type="submit" onclick="return confirm('Yakin ingin menghapus data?')"><i class="fas fa-minus-circle"></i></button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$(function() {
$('#users-table').DataTable();
});
</script>
@endpush

resources/views/gates/show.blade.php
@extends('layouts.app')

@section('content')
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMyjXZUcSAiFz2j_qf7K1HLof1tgl_RsU&libraries=places&language=id"></script>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="mt-5">Detail Gates</h1>

            <div class="card">
                    <div class="card-body">
                    <p class="card-text">{{ $gate->gate_name }}</p>
                    <h5 class="card-title">{{ $gate->radius }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ $gate->list_adress }}</h6>
                    <p class="card-text">{{ $gate->langitude }}</p>
                    <p class="card-text">{{ $gate->longitude }}</p>



                    <div class="card-header">Our Location</div>
                    <div id="map" style="height: 500px; width:100%;"></div>
                    {{-- <div style="width: 1000px; height: 500px;"> --}}
                        {{-- {!! Mapper::render() !!} --}}
                    </div>

                    {{-- <a href="{{ $gate->id }}/edit" class="btn btn-primary btn-sm">edit</a>
                    <form action="/gate/{{ $gate->id }}" method="post" class="d-inline">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-danger btn-sm">delete</button>
                    </form> --}}
                    <a href="/gates" class="card-link btn-sm "><i class="fas fa-undo-alt"></i> back</a>
                    <td>
                    </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('customjs')
    <script>
        var markers = [];
        var marker;
        var cityCircle;
        var cityCircles = [];

        function initialize() {
            geocoder = new google.maps.Geocoder();
            var mapOptions = {
                center: new google.maps.LatLng({{$gate->langitude}}, {{$gate->longitude}}),
                zoom: 15
            };
            var myLatLng = {lat: {{$gate->langitude}}, lng: {{$gate->longitude}} };
            map = new google.maps.Map(document.getElementById("map"),
                    mapOptions);

            var input = document.getElementById('autocomplete');

            var options = {
                types: ['address']
            };
            autocomplete = new google.maps.places.Autocomplete(input, options);
            autocomplete.bindTo('bounds', map);
            var infowindow = new google.maps.InfoWindow();
            @foreach($gate['distance'] as $flyers)

            var myLatLngs = {lat: {{$flyers->langitude}}, lng: {{$flyers->longitude}} };
                markers = new google.maps.Marker({
                        map: map,
                        draggable: false,
                        position: new google.maps.LatLng(myLatLngs),
                        anchorPoint: new google.maps.Point(0, -29)
                });

            @endforeach
            cityCircle = new google.maps.Circle({
                strokeColor: '#FF0000',
                strokeOpacity: 0.8,
                strokeWeight: 2,
                fillColor: '#FF0000',
                fillOpacity: 0.35,
                map: map,
                center:  myLatLng,
                radius: Math.sqrt(5) * 100
            });
            marker = new google.maps.Marker({
                        map: map,
                        draggable: false,
                        position: new google.maps.LatLng(myLatLng),
                        anchorPoint: new google.maps.Point(0, -29)
                });

            // fungsi ketika marekr di gerakan mengambil alamat lengkap dan di isikan di text box alamat
            google.maps.event.addListener(marker, 'dragend', function (event) {


                geocoder.geocode({
                    'latLng': event.latLng
                }, function(results, status) {
                    // bersihkan dahulu isi dari textbox karena akan di ganti menjadi yang terbaru
                    $('#langitude').val('');
                    $('#longitude').val('');
                    $('#autocomplete').val('');

                    // sesudah di bersihkan baru di isi kembali oleh value berikut
                    var marker_positions = marker.getPosition();

                    $('#langitude').val(marker_positions.lat());
                    $('#longitude').val(marker_positions.lng());
                    $('#autocomplete').val(results[0].formatted_address);
                    cityCircle = new google.maps.Circle({
                        strokeColor: '#FF0000',
                        strokeOpacity: 0.8,
                        strokeWeight: 2,
                        fillColor: '#FF0000',
                        fillOpacity: 0.35,
                        map: map,
                        center:  marker_positions,
                        radius: Math.sqrt(5) * 100
                    });
                    cityCircles.push(cityCircle);

                // tidak lupa untuk menampilkan label alamat tepat di atas markernya
                var address = '';
                    if (results[0].address_components) {
                        address = [
                            (results[0].address_components[0] && results[0].address_components[0].short_name || ''),
                            (results[0].address_components[1] && results[0].address_components[1].short_name || ''),
                            (results[0].address_components[2] && results[0].address_components[2].short_name || '')
                        ].join(' ');
                    }
                    infowindow.setContent('<div><strong>' + address + '</strong>');
                    infowindow.open(map, marker);
                })
            });

            autocomplete.addListener('place_changed', function () {
                  // hapus marker
                deleteMarkers();

                var place = this.getPlace();
                if (!place.geometry) {
                    window.alert("Autocomplete's returned place contains no geometry");
                    return;
                }

                // If the place has a geometry, then present it on a map.
                if (place.geometry.viewport) {
                    map.fitBounds(place.geometry.viewport);
                } else {
                    map.setCenter(place.geometry.location);
                    map.setZoom(17);
                }

                $('#langitude').val(place.geometry.location.lat());
                $('#longitude').val(place.geometry.location.lng());
                map.setCenter(place.geometry.location);//center the map over the result

                    // if marker exists and has a .setMap method, hide it or clear old marker
                if (marker && marker.setMap) {
                    marker.setMap(null);
                }

                marker = new google.maps.Marker(
                        {
                            map: map,
                            draggable: true,
                            animation: google.maps.Animation.DROP,
                            position: place.geometry.location
                        });

                markers.push(marker);
                cityCircle = new google.maps.Circle({
                        strokeColor: '#FF0000',
                        strokeOpacity: 0.8,
                        strokeWeight: 2,
                        fillColor: '#FF0000',
                        fillOpacity: 0.35,
                        map: map,
                        center:  place.geometry.location,
                        radius: Math.sqrt(5) * 100
                    });
                    cityCircles.push(cityCircle);

                    // fungsi ketika marekr di gerakan mengambil alamat lengkap dan di isikan di text box alamat
                google.maps.event.addListener(marker, 'dragend', function (event) {
                geocoder.geocode({
                'latLng': event.latLng
                }, function(results, status) {
                // bersihkan dahulu isi dari textbox karena akan di ganti menjadi yang terbaru
                $('#langitude').val('');
                $('#longitude').val('');
                $('#autocomplete').val('');

              // sesudah di bersihkan baru di isi kembali oleh value berikut
                var marker_positions = marker.getPosition();

                $('#langitude').val(marker_positions.lat());
                $('#longitude').val(marker_positions.lng());
                $('#autocomplete').val(results[0].formatted_address);

              // tidak lupa untuk menampilkan label alamat tepat di atas markernya
              var address = '';
                if (results[0].address_components) {
                    address = [
                        (results[0].address_components[0] && results[0].address_components[0].short_name || ''),
                        (results[0].address_components[1] && results[0].address_components[1].short_name || ''),
                        (results[0].address_components[2] && results[0].address_components[2].short_name || '')
                    ].join(' ');
                }
                infowindow.setContent('<div><strong>' + address + '</strong>');
                infowindow.open(map, marker);
              })
                  });

                var address = '';
                if (place.address_components) {
                    address = [
                        (place.address_components[0] && place.address_components[0].short_name || ''),
                        (place.address_components[1] && place.address_components[1].short_name || ''),
                        (place.address_components[2] && place.address_components[2].short_name || '')
                    ].join(' ');
                }

                infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
                infowindow.open(map, marker);
            });
        }

        google.maps.event.addDomListener(window, 'load', initialize);


    </script>
@endsection