routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Route::get('/', 'MapController@index');

//Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::resource('gates', 'ListsController');

Route::resource('branches', 'BranchController');

Route::resource('roads', 'RoadsController');

Route::resource('virtuals', 'VirtualController');

Route::resource('details', 'DetailController');


Route::get('/map', 'MapController@index');

Route::get('gates/branch_detail/{id}', 'ListsController@branch_detail')->name('branch_detail');
Route::get('details/gate_info/{id}', 'DetailController@gate_info')->name('gate_info');
Route::get('details/virtual/{id}', 'DetailController@virtual')->name('gate_code');
Route::get('details/gate_maps/{id}', 'DetailController@gate_maps')->name('gate_maps');

app/Virtual.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Virtual extends Model
{
    protected $fillable = ['vg_code','virtual_gantry','vg_type','gate_info','v_address','langitude','longitude','radius'];
}

app/Http/Controllers/VirtualController.php
<?php

namespace App\Http\Controllers;

use App\Gate;
use App\Virtual;
use Illuminate\Http\Request;
use DB;

class VirtualController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $virtuals=Virtual::all();
        return view('virtuals.index', compact('virtuals'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {


        $data['filtergate'] = Gate::select('gate_code','gate_name')->get();
            //  dd($data['filtergate']);

        return view('virtuals.insertvirtuals',$data);
    }
         /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'gate_info'=>'required',
            'vg_code'=>'required',
            'virtual_gantry'=>'required',
            'vg_type'=>'required',
            'v_address'=>'required',
            'langitude'=>'required',
            'longitude'=>'required'
        ]);

        $road=Virtual::create($request->all());
        return redirect()->route('virtuals.index')->with('pesan', 'berhasil hore');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\list  $list
     * @return \Illuminate\Http\Response
     */
    public function show(Virtual $virtual)
    {
        // $lat=DB::select('call distance(?)',array(8700)
        // );
        // $gate['distance']=$lat;
        $gates=DB::select('select * from public.distance()');

        // $gate = Gate::select('id','list_name','langitude','longitude',
        //         DB::raw('( 3959 * ACOS(COS(RADIANS(37))
        //         * COS (RADIANS(langitude))
        //         * COS(RADIANS(longitude)
        //         - RADIANS(-122))
        //         + SIN(RADIANS(37))
        //         * SIN(RADIANS(langitude)) ) )) AS distance')
        //         )->get();


        // Mapper::map($gate->langitude, $gate->longitude, ['draggable' => false]);
        // Mapper::map(
        //     -6.200000, 106.816666,
        //     [
        //     'draggable' => true,
        //     'eventDragEnd' => 'test_js(this.getPosition().lat(), this.getPosition().lng());'
        //     ]);

        return view('virtuals.show', compact('virtual'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\list  $list
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $virtuals=Virtual::findOrfail($id);
        $data['filtergate'] = Gate::select('gate_code','gate_name')->get();


        // $lat=DB::select('call distance(?)',array(8700)
        // );
        // $gates['distance']=$lat;
        // dd($gates['distance']);


        return view('virtuals.edit', compact('virtuals'),$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\list  $list
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'gate_info'=>'required',
            'vg_code'=>'required',
            'virtual_gantry'=>'required',
            'vg_type'=>'required',
            'v_address'=>'required',
            'langitude'=>'required',
            'longitude'=>'required'
        ]);

        $virtual=Virtual::find($id);
        $virtual->update($request->all());
        return redirect()->route('virtuals.index')->with('pesan', 'data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\list  $list
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $virtual=Virtual::find($id);
        $virtual->delete();
        return redirect()->route('virtuals.index')->with('pesan', 'data berhasil dihapus');

    }

}

resources/views/virtuals/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">List Virtual Gantry</div>
                    @include('notif')
                    <div class ="card-body">
                        <th><a href=" {{ route('virtuals.create') }}" class="btn btn-primary btn-sm" ><i class="fas fa-plus-circle"></i> Create New Virtual Gantry</a></th>
                    </div>
                        <table class="table table-bordered" id="users-table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Gate Info</th>
                                    <th>Virtual Gate Code</th>
                                    <th>Virtual Gantry</th>
                                    <th>Virtual Gate Type</th>
                                    <th>V Address</th>
                                    <th>Lattitude</th>
                                    <th>Langitude</th>
                                    <th>Radius</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ( $virtuals as $virtual )
                                <tr>
                                    <th>{{ $loop->iteration }}</th>
                                    <th>{{ $virtual->gate_info }}</th>
                                    <th>{{ $virtual->vg_code }}</th>
                                    <th>{{ $virtual->virtual_gantry }}</th>
                                    <th>{{ $virtual->vg_type }}</th>
                                    <th>{{ $virtual->v_address }}</th>
                                    <th>{{ $virtual->langitude }}</th>
                                    <th>{{ $virtual->longitude }}</th>
                                    <th>{{ $virtual->radius }}</th>


                                    <td>
                                        {!! Form::open(['route'=>['virtuals.destroy',$virtual->id],'method'=>'DELETE']) !!}
                                        <a href="{{ route('virtuals.show',$virtual->id) }}" class="btn"><i class="fas fa-info-circle"></i></a>
                                        <a href=" {{ route('virtuals.edit',$virtual->id) }}" class="btn"><i class="fas fa-edit"></i></a>
                                        <button class="btn" type="submit" onclick="return confirm('Yakin ingin menghapus data?')"><i class="fas fa-minus-circle"></i></button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$(function() {
$('#users-table').DataTable();
});
</script>
@endpush

resources/views/virtuals/show.blade.php
@extends('layouts.app')

@section('content')
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMyjXZUcSAiFz2j_qf7K1HLof1tgl_RsU&libraries=places&language=id"></script>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="mt-5">Detail Virtual</h1>

            <div class="card">
                    <div class="card-body">
                    <p class="card-text">{{ $virtual->gate_info }}</p>
                    <h5 class="card-title">{{ $virtual->vg_code }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ $virtual->virtual_gantry }}</h6>
                    <p class="card-text">{{ $virtual->vg_type }}</p>
                    <p class="card-text">{{ $virtual->v_address }}</p>
                    <p class="card-text">{{ $virtual->langitude }}</p>
                    <p class="card-text">{{ $virtual->longitude }}</p>
                    <p class="card-text">{{ $virtual->radius }}</p>



                    {{-- <div class="card-header">Our Location</div>
                    <div id="map" style="height: 500px; width:100%;"></div>
                    {{-- <div style="width: 1000px; height: 500px;"> --}}
                        {{-- {!! Mapper::render() !!} --}}
                    {{-- </div> --}}

                    {{-- <a href="{{ $gate->id }}/edit" class="btn btn-primary btn-sm">edit</a>
                    <form action="/gate/{{ $gate->id }}" method="post" class="d-inline">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-danger btn-sm">delete</button>
                    </form> --}}
                    <a href="/virtuals" class="card-link btn-sm "><i class="fas fa-undo-alt"></i> back</a>
                    <td>
                    </div>
            </div>
        </div>
    </div>
</div>
@endsection

{{-- @section('customjs')
    <script>
        var markers = [];
        var marker;
        var cityCircle;
        var cityCircles = [];

        function initialize() {
            geocoder = new google.maps.Geocoder();
            var mapOptions = {
                center: new google.maps.LatLng({{$gate->langitude}}, {{$gate->longitude}}),
                zoom: 15
            };
            var myLatLng = {lat: {{$gate->langitude}}, lng: {{$gate->longitude}} };
            map = new google.maps.Map(document.getElementById("map"),
                    mapOptions);

            var input = document.getElementById('autocomplete');

            var options = {
                types: ['address']
            };
            autocomplete = new google.maps.places.Autocomplete(input, options);
            autocomplete.bindTo('bounds', map);
            var infowindow = new google.maps.InfoWindow();
            @foreach($gate['distance'] as $flyers)

            var myLatLngs = {lat: {{$flyers->langitude}}, lng: {{$flyers->longitude}} };
                markers = new google.maps.Marker({
                        map: map,
                        draggable: false,
                        position: new google.maps.LatLng(myLatLngs),
                        anchorPoint: new google.maps.Point(0, -29)
                });

            @endforeach
            cityCircle = new google.maps.Circle({
                strokeColor: '#FF0000',
                strokeOpacity: 0.8,
                strokeWeight: 2,
                fillColor: '#FF0000',
                fillOpacity: 0.35,
                map: map,
                center:  myLatLng,
                radius: Math.sqrt(5) * 100
            });
            marker = new google.maps.Marker({
                        map: map,
                        draggable: false,
                        position: new google.maps.LatLng(myLatLng),
                        anchorPoint: new google.maps.Point(0, -29)
                });

            // fungsi ketika marekr di gerakan mengambil alamat lengkap dan di isikan di text box alamat
            google.maps.event.addListener(marker, 'dragend', function (event) {


                geocoder.geocode({
                    'latLng': event.latLng
                }, function(results, status) {
                    // bersihkan dahulu isi dari textbox karena akan di ganti menjadi yang terbaru
                    $('#langitude').val('');
                    $('#longitude').val('');
                    $('#autocomplete').val('');

                    // sesudah di bersihkan baru di isi kembali oleh value berikut
                    var marker_positions = marker.getPosition();

                    $('#langitude').val(marker_positions.lat());
                    $('#longitude').val(marker_positions.lng());
                    $('#autocomplete').val(results[0].formatted_address);
                    cityCircle = new google.maps.Circle({
                        strokeColor: '#FF0000',
                        strokeOpacity: 0.8,
                        strokeWeight: 2,
                        fillColor: '#FF0000',
                        fillOpacity: 0.35,
                        map: map,
                        center:  marker_positions,
                        radius: Math.sqrt(5) * 100
                    });
                    cityCircles.push(cityCircle);

                // tidak lupa untuk menampilkan label alamat tepat di atas markernya
                var address = '';
                    if (results[0].address_components) {
                        address = [
                            (results[0].address_components[0] && results[0].address_components[0].short_name || ''),
                            (results[0].address_components[1] && results[0].address_components[1].short_name || ''),
                            (results[0].address_components[2] && results[0].address_components[2].short_name || '')
                        ].join(' ');
                    }
                    infowindow.setContent('<div><strong>' + address + '</strong>');
                    infowindow.open(map, marker);
                })
            });

            autocomplete.addListener('place_changed', function () {
                  // hapus marker
                deleteMarkers();

                var place = this.getPlace();
                if (!place.geometry) {
                    window.alert("Autocomplete's returned place contains no geometry");
                    return;
                }

                // If the place has a geometry, then present it on a map.
                if (place.geometry.viewport) {
                    map.fitBounds(place.geometry.viewport);
                } else {
                    map.setCenter(place.geometry.location);
                    map.setZoom(17);
                }

                $('#langitude').val(place.geometry.location.lat());
                $('#longitude').val(place.geometry.location.lng());
                map.setCenter(place.geometry.location);//center the map over the result

                    // if marker exists and has a .setMap method, hide it or clear old marker
                if (marker && marker.setMap) {
                    marker.setMap(null);
                }

                marker = new google.maps.Marker(
                        {
                            map: map,
                            draggable: true,
                            animation: google.maps.Animation.DROP,
                            position: place.geometry.location
                        });

                markers.push(marker);
                cityCircle = new google.maps.Circle({
                        strokeColor: '#FF0000',
                        strokeOpacity: 0.8,
                        strokeWeight: 2,
                        fillColor: '#FF0000',
                        fillOpacity: 0.35,
                        map: map,
                        center:  place.geometry.location,
                        radius: Math.sqrt(5) * 100
                    });
                    cityCircles.push(cityCircle);

                    // fungsi ketika marekr di gerakan mengambil alamat lengkap dan di isikan di text box alamat
                google.maps.event.addListener(marker, 'dragend', function (event) {
                geocoder.geocode({
                'latLng': event.latLng
                }, function(results, status) {
                // bersihkan dahulu isi dari textbox karena akan di ganti menjadi yang terbaru
                $('#langitude').val('');
                $('#longitude').val('');
                $('#autocomplete').val('');

              // sesudah di bersihkan baru di isi kembali oleh value berikut
                var marker_positions = marker.getPosition();

                $('#langitude').val(marker_positions.lat());
                $('#longitude').val(marker_positions.lng());
                $('#autocomplete').val(results[0].formatted_address);

              // tidak lupa untuk menampilkan label alamat tepat di atas markernya
              var address = '';
                if (results[0].address_components) {
                    address = [
                        (results[0].address_components[0] && results[0].address_components[0].short_name || ''),
                        (results[0].address_components[1] && results[0].address_components[1].short_name || ''),
                        (results[0].address_components[2] && results[0].address_components[2].short_name || '')
                    ].join(' ');
                }
                infowindow.setContent('<div><strong>' + address + '</strong>');
                infowindow.open(map, marker);
              })
                  });

                var address = '';
                if (place.address_components) {
                    address = [
                        (place.address_components[0] && place.address_components[0].short_name || ''),
                        (place.address_components[1] && place.address_components[1].short_name || ''),
                        (place.address_components[2] && place.address_components[2].short_name || '')
                    ].join(' ');
                }

                infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
                infowindow.open(map, marker);
            });
        }

        google.maps.event.addDomListener(window, 'load', initialize);


    </script>
@endsection --}}